name: CI Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m venv myenv
        source myenv/bin/activate
        pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Backend Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}  # Access the secret here
      run: |
        source myenv/bin/activate
        cd backend
        export PYTHONPATH=$(pwd)
        pytest -vv --tb=short tests/unit
